version: "2"

volumes:
    data:
    nginx:

services:

    web:
        image: nginx:stable-alpine
        working_dir: /application
        volumes:
            - data:/application
            - nginx:/etc/nginx/conf.d
        ports:
            - 80

    php-fpm:
        build: php-fpm
        working_dir: /application
        volumes:
            - data:/application
