version: "2"

volumes:
    data:

services:

    web:
        build: nginx
        working_dir: /application
        volumes:
            - data:/application
        ports:
            - 80
        labels:
            "traefik.enable": "true"
            "traefik.frontend.entryPoints": "http,https"
            "traefik.frontend.rule": "Host: ${APP_HOSTNAME:example.com}"

    php-fpm:
        build: php-fpm
        working_dir: /application
        volumes:
            - data:/application
